### ISSUE TITLE
Admin: Question management (Add Question)

### ISSUE THREAD

**Issue by nerkarrajesh** [thungasr/BigBang_ASQ2.0#7]
Not able to add question to any models.
![screen shot 2015-12-14 at 6 31 09 pm](https://cloud.githubusercontent.com/assets/15698518/11800398/e105a0ae-a290-11e5-8c3f-0e5741b9b3d9.png)

**Comment by saivasu007** [comment]
Thanks..I have verified on my end and this is a valid BUG in the application.I will let you know once the fix is available for your testing.

**Comment by saivasu007** [comment]
Fix for this issue has been taken care and changes are applied to source.Please go-ahead and get the latest updates and confirm the bug fix.
Thanks.
