### ISSUE TITLE
Reset Password email Link Not working

### ISSUE THREAD

**Issue by nerkarrajesh** [thungasr/BigBang_ASQ2.0#8]
On clicking the reset password link in the email it opens as a blank page.
![screen shot 2015-12-20 at 9 08 00 am](https://cloud.githubusercontent.com/assets/15698518/11918984/cd8b9692-a6f9-11e5-8059-95eb6186950f.png)

**Comment by saivasu007** [comment]
Hi,
      I have looked into the details and didn't find any issues with Password Reset screen.After clicking the link I can see "Password Reset" screen displaying without any issues.Please refer the attached and let me know.

![screen shot 2015-12-20 at 10 45 58 am](https://cloud.githubusercontent.com/assets/15098500/11919416/01e452f0-a707-11e5-8ddc-e28404b5e3ff.png)

**Comment by saivasu007** [comment]
Please make sure you have updated code on your workspace and try one more time with Mozilla browser.If you see everything is working fine then please go-ahead and close the bug.
